{
 "title": "Stream-Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Active Test Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "stream_monitor_active_tests" }
   ]
  },
  {
   "title": "Successful Tests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(stream_monitor_total_tests{status=\"success\"}[$__range])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Failed Tests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(stream_monitor_total_tests{status=\"failure\"}[$__range])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Peak Segment Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (region)(stream_monitor_segment_duration_seconds)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Peak Startup Latency by Region",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(region)(stream_monitor_test_startup_seconds)",
     "legendFormat": "{{region}}"
    }
   ]
  },
  {
   "title": "Peak Segment Latency By Variant",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (variant)(stream_monitor_latency_seconds)",
     "legendFormat": "{{variant}}"
    }
   ]
  },
  {
   "title": "Active Sessions by Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max by(region)(stream_monitor_active_tests)",
     "legendFormat": "{{region}}"
    }
   ]
  }
 ]
}